shamefullyHoist: true

allowBuilds:
  'sharp': true
  'unrs-resolver': true
  '@parcel/watcher': true
  'esbuild': false
  'vue-demi': false
  'maplibre-gl': false

minimumReleaseAgeExclude:
  - '@nuxt-ignis/content'
  - '@nuxt-ignis/db'
  - '@nuxt-ignis/default'
  - '@nuxt-ignis/forms'
  - '@nuxt-ignis/ui'
  - '@nuxt-ignis/utils'
  - '@nuxt-ignis/validation'
  - 'nuxt-ignis'
